### PR TITLE
Added 'Auto Smoker' Ability

### PR DESCRIPTION
**Pull request by jade-clarke**
Added 'Auto Smelter' ability to Blazegold Sword as per Issue #30

### CODE REVIEW

**Comment by Direwolf20-MC** [comment]
Hey this looks pretty good :). Unfortunately I just so happened to be in the middle of changing around where some of these files live in the branch I was working in. Would you mind resubmitting the PR based on the current main branch? That way you get the credit for the PR :).  

Thank you!

**Comment by jade-clarke** [comment]
I have synced with your changes and rebased on top. I added it to the Celestigem and Eclipse Alloy swords to confirm there are no conflicts with the Drops Teleporter ability.

I demo'd this [here](https://youtu.be/ektDPVrp-Hc)

**Comment by jade-clarke** [comment]
Had a sneaking suspicion that I might need to rerun the datagen. Can confirm now that everything is up to date.
@Direwolf20-MC

**Comment by jade-clarke** [comment]
After reading some of the comments on your spotlight videos, it seems there may also be an interest in adding a rotten flesh to leather recipe.

How would you feel about me adding this to `JustDireRecipes.java`?:
```java
SimpleCookingRecipeBuilder.smoking(Ingredient.of(Items.ROTTEN_FLESH), RecipeCategory.MISC, Items.LEATHER, 1.0f, 200);
```

**Comment by Direwolf20-MC** [comment]
Thank you :). For now let’s hold off on the leather recipe. I may wind up adding something else for that but conceptually I’d like the smelting recipes to only do regular smelting and not add one-offs :). 

Thanks for the PR! I’ll take a look at it later today :).

**Comment by Direwolf20-MC** [comment]
Merged - thank you!! :)

**Pull request merged**
